### ISSUE TITLE
Example of how to compute gradient numerically?

### ISSUE THREAD

**Issue by mcreel** [tpapp/DynamicHMCExamples.jl#15]
I am working on an example of estimation of a stochastic volatility model using simulated moments. It is working very well, and when I'm done experimenting I will present a pull request for possible inclusion as an example. However, it is currently quite time-consuming. I would like to try using the numeric gradient of the log posterior, instead of AD, to see if it's possibly faster. AD is forced to track many values, due to the many simulations. On the other hand, finite difference gradients can be computed with only 4 log posterior evaluations (3 parameters). I suspect it may be faster to do it that way. As I understand it, great accuracy of the gradient evaluations is probably not too important for NUTS. Would it be possibly to give an example of how to compute the gradient numerically for one of the existing examples?

**Comment by tpapp** [comment]
I am reluctant to give an example using FD in this package, it is almost always inferior to analytical gradients (which are usually well worth it) or AD.

That said, if you want to provide custom gradients of any kind, then something along the lines of this could work:
```julia
using LogDensityProblems

function LogDensityProblems.logdensity(vgb::LogDensityProblems.ValueGradientBuffer,
                                       ℓ::YourProblem, x::AbstractVector{T})
    gradient = vgb.buffer
    v0 = logdensity(Value, ℓ, x)
    ϵ = 1e-6
    x′ = copy(x)
    for i in axes(x, 1)
        x′[i] = x[i] + ϵ
        gradient[i] = (logdensity(Value, ℓ, x′) - v0) / ϵ
        x′[i] = x[i]
    end
    ValueGradient(oftype(eltype(gradient), v0), gradient)
end
```

This is untested (you may have to tweak it), and takes not shortcuts for `-Inf` etc.

But again, I would invest the time in analytical derivatives.

**Comment by mcreel** [comment]
Thanks very much. I agree that AD is an atttractive solution in general, but I just wanted to investigate this particular application in more detail. With your suggestion, I think I will be able to do so.

**Comment by tpapp** [comment]
Glad to help. But I think that the real solution in these cases is analytical/manual derivatives. `Base.isapprox` is supported for `ValueGradient` so you can easily test analytical and FD differences against those obtained with eg `ForwardDiff`.
