### ISSUE TITLE
a question about unpacking the parameters

### ISSUE THREAD

**Issue by JackRab** [tpapp/DynamicHMCExamples.jl#27]
Hi Tamas,

I just have a question on your worked example. Please forgive me if this sounds silly. In the worked example, you define a *callable* like this
```julia
function (problem::BernoulliProblem)(θ)
    @unpack α = θ               # extract the parameters
    @unpack n, s = problem       # extract the data
    # log likelihood, with constant terms dropped
    s * log(α) + (n-s) * log(1-α)
end
```
And then evaluate 
```julia
p = BernoulliProblem(20, 10)
p((α = 0.5, )) # make sure that it works
```

I just wonder why we need to `unpack` α? Can we just define the *callable* like this
```julia
function (problem::BernoulliProblem)(α)
    @unpack n, s = problem       # extract the data
    # log likelihood, with constant terms dropped
    s * log(α) + (n-s) * log(1-α)
end
```
And then evaluate
```julia
p = BernoulliProblem(20, 10)
p(0.5) # make sure that it works
```
which looks a little bit clearer for me. There must be some additional rational/thinking why we did the `unpack` α. Can you please help me understand that? Please correct me if something is wrong.

Thanks.

**Comment by tpapp** [comment]
DynamicHMC.jl uses the API from LogDensityProblems.jl, which maps a *vector* in `ℝⁿ` (unconstrained) to a log density (and its gradient). Moreover, a lot of the examples use transformations (from TransformVariables.jl), which map `ℝⁿ` to some parameters, delivered as a `NamedTuple` in the example above, which help you construct such a callable.

So while you could indeed define the callable to just take an `α`, you would need to do the transformation a bit differently. The reason I did it this way in the manual is to make it consistent with more complex problems that have multiple parameters.

**Comment by JackRab** [comment]
I see. Thanks.
