### ISSUE TITLE
Invalid chars in example?

### ISSUE THREAD

**Issue by xukai92** [tpapp/DynamicHMCExamples.jl#4]
In https://github.com/tpapp/DynamicHMCExamples.jl/blob/master/src/example_independent_bernoulli.jl#L52 we have:

```julia
P = TransformedBayesianProblem(to_tuple((α = to_𝕀,)), p);
```

I wonder what is `to_𝕀` here?

**Comment by tpapp** [comment]
The examples have been updated to reflect the new API. ` to_𝕀` is now `as𝕀`, and it denotes a transformation from the real line to the `[0,1]` interval.
